name: tests-payments

on:
  pull_request
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo $STRIPE_KEY
        env:
          STRIPE_KEY: ${{ secrets.STRIPE_KEY }}

